name: Build

on:
  workflow_dispatch:
    inputs:
      # 利用する Unity Editor のバージョンを上書きする場合はバージョン名を指定
      unity_editor_version_override:
        type: string
        required: false
        default: ''
        description: '利用する Unity バージョン (Optional)'
      # iOS ビルドをするかどうか
      build_for_ios:
        type: boolean
        required: false
        default: true
        description: 'iOS ビルド'
      # Android ビルドをするかどうか
      build_for_android:
        type: boolean
        required: false
        default: true
        description: 'Android ビルド'
  
jobs:
  prepare:
    runs-on:
    - self-hosted
    - individual

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Unity Editor
      uses: monry/github_actions/.github/actions/unity/install_editor@experimental
      with:
        unity_editor_version_override: ${{ inputs.unity_editor_version_override }}
        unity_editor_modules: "${{ inputs.build_for_ios && 'ios ' || '' }}${{ inputs.build_for_android && 'android ' || '' }}"

  cleanup:
    runs-on:
      - self-hosted
      - individual
    needs: prepare
    if: always()
    steps:
    - name: Cleanup Git Config
      uses: monry/github_actions/.github/actions/git/cleanup_config@experimental
