name: Build

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on:
    - self-hosted
    - individual

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Unity Editor
      uses: monry/github_actions/.github/actions/unity/install_editor@experimental

  cleanup:
    runs-on:
      - self-hosted
      - individual
    needs: prepare
    if: always()
    steps:
    - name: Cleanup Git Config
      uses: monry/github_actions/.github/actions/git/cleanup_config@experimental