name: Build

on:
  workflow_dispatch:
    inputs:
      # 利用する Unity Editor のバージョンを上書きする場合はバージョン名を指定
      unity_editor_version_override:
        type: string
        required: false
        default: ''
        description: '利用する Unity バージョン (Optional)'
      # iOS ビルドをするかどうか
      build_for_ios:
        type: boolean
        required: false
        default: true
        description: 'iOS ビルド'
      # Android ビルドをするかどうか
      build_for_android:
        type: boolean
        required: false
        default: true
        description: 'Android ビルド'
  
jobs:
  prepare:
    runs-on:
    - self-hosted
    - individual
    outputs:
      unity_editor_version: ${{ steps.prepare_for_build.outputs.unity_editor_version }}
      target_platforms: ${{ steps.prepare_for_build.outputs.target_platforms }}

    steps:
    - uses: DeNA/setup-job-workspace-action@v2
    - name: Checkout
      uses: actions/checkout@v4
      with:
        clean: false
        submodules: false
        persist-credentials: false
        set-safe-directory: false
        fetch-depth: 0
    - name: Prepare for Build
      id: prepare_for_build
      uses: monry/github_actions/.github/actions/unity/prepare@implement-with-csharp
      with:
        unity_editor_version_override: ${{ inputs.unity_editor_version_override }}
        target_platforms: "${{ inputs.build_for_ios && 'iOS,' || '' }}${{ inputs.build_for_android && 'Android,' || '' }}"

  build:
    runs-on:
    - self-hosted
    - individual
    needs: prepare
    strategy:
      matrix:
        target_platform: ${{ fromJson(needs.prepare.outputs.target_platforms) }}
    steps:
    - uses: DeNA/setup-job-workspace-action@v2
    - name: Checkout
      uses: actions/checkout@v4
      with:
        clean: false
        submodules: false
        persist-credentials: false
        set-safe-directory: false
        fetch-depth: 0
    - name: Build
      uses: monry/github_actions/.github/actions/unity/build/player@implement-with-csharp
      with:
        unity_editor_version: ${{ needs.prepare.outputs.unity_editor_version }}
        target_platform: ${{ matrix.target_platform }}
